-- Migration: Create Consultation Form Forms Table
-- Description: Comprehensive medical history intake form capturing patient symptoms, cardiovascular history, and comorbid conditions
-- Created: 2025-12-30
-- Generated by: form_converter tool

-- ==============================================================================
-- CREATE CONSULTATION_FORM_FORMS TABLE
-- ==============================================================================

CREATE TABLE IF NOT EXISTS consultation_form_forms (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  patient_id UUID NOT NULL REFERENCES patients(id) ON DELETE CASCADE,
  appointment_id UUID REFERENCES appointments(id) ON DELETE SET NULL,

  -- Form metadata
  form_type TEXT CHECK (form_type IN ('pre_consultation', 'during_consultation')),
  status TEXT CHECK (status IN ('draft', 'partial', 'completed')) DEFAULT 'draft',
  filled_by UUID REFERENCES auth.users(id), -- NULL if patient, doctor_id if doctor-filled

  -- Reference to shared health records (prevents duplication)
  vitals_record_id UUID REFERENCES patient_vitals(id),

  -- Consultation Form-specific fields (JSONB for flexibility - no schema updates needed)
  consultation_form_data JSONB NOT NULL DEFAULT '{}',

  -- Timestamps
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now(),
  created_by UUID REFERENCES auth.users(id),
  updated_by UUID REFERENCES auth.users(id)
);

-- Create indexes for common queries
CREATE INDEX idx_consultation_form_forms_patient ON consultation_form_forms(patient_id);
CREATE INDEX idx_consultation_form_forms_appointment ON consultation_form_forms(appointment_id);
CREATE INDEX idx_consultation_form_forms_status ON consultation_form_forms(status);
CREATE INDEX idx_consultation_form_forms_form_type ON consultation_form_forms(form_type);

-- JSONB GIN index for querying nested fields efficiently
CREATE INDEX idx_consultation_form_data ON consultation_form_forms USING gin(consultation_form_data);

-- Add column comments for documentation
COMMENT ON TABLE consultation_form_forms IS 'Comprehensive medical history intake form capturing patient symptoms, cardiovascular history, and comorbid conditions';
COMMENT ON COLUMN consultation_form_forms.form_type IS 'When form is filled: pre_consultation (patient) or during_consultation (doctor)';
COMMENT ON COLUMN consultation_form_forms.status IS 'Form completion status: draft, partial, completed';
COMMENT ON COLUMN consultation_form_forms.filled_by IS 'NULL if filled by patient, doctor user_id if filled by doctor';
COMMENT ON COLUMN consultation_form_forms.vitals_record_id IS 'Reference to shared patient_vitals table (prevents duplication)';
COMMENT ON COLUMN consultation_form_forms.consultation_form_data IS 'JSONB containing all consultation_form-specific fields (flexible schema)';

-- ==============================================================================
-- CONSULTATION_FORM_DATA JSONB STRUCTURE (DOCUMENTED)
-- ==============================================================================
-- {

--   "history_and_presentation": {


--   },

--   "symptom_characteristics": {


--   },

--   "prior_cardiovascular_history": {


--   },

--   "comorbid_disease": {


--   },

--   "other": {

--     "treatment_history": "Long text description...",  // Free text field for documenting prior treatment history

--     "pulse": 150,  // Patient's pulse rate

--     "pulse_per_min": 150,  // Patient's pulse rate per minute

--     "examination_description": "Long text description...",  // Detailed description of examination findings

--     "carotid_right": "Carotid - Right",  // Right carotid pulse examination findings


--     // ... 22 more fields

--   },

-- }
-- ==============================================================================

-- ==============================================================================
-- CREATE TRIGGER FOR UPDATED_AT
-- ==============================================================================

CREATE OR REPLACE FUNCTION update_consultation_form_forms_timestamp()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trigger_update_consultation_form_forms_timestamp
  BEFORE UPDATE ON consultation_form_forms
  FOR EACH ROW
  EXECUTE FUNCTION update_consultation_form_forms_timestamp();

-- ==============================================================================
-- MIGRATION NOTES
-- ==============================================================================
-- This table implements the JSONB-based flexible schema approach:
-- - No schema updates needed to add new fields
-- - GIN index enables fast JSONB queries
-- - References shared health records (vitals) to prevent duplication
-- - Field registration in field_definitions table happens at application layer
--
-- Benefits:
-- 1. Rapid iteration - add fields without migrations
-- 2. Type safety - validated by TypeScript interfaces
-- 3. Performance - GIN indexes provide fast queries
-- 4. No duplication - shared data stored in generic tables
--
-- Next steps:
-- - Update form_schemas.py with CONSULTATION_FORM_FORM_SCHEMA
-- - Create TypeScript interfaces (Consultation FormFormData)
-- - Build Consultation FormPreConsultationForm component
-- - Implement useConsultation FormForms hook
-- - Add field registration logic
-- ==============================================================================